### ISSUE TITLE
Shared library code?

### ISSUE THREAD

**Issue by Reconcyl** [anojs/anojs#3]
The current appeal of the project is the ability to embed any animation with 2 lines of code. If we lift this restriction slightly by introducing an additional helper library, it could greatly simplify the rest of the animation scripts.

The library could be structured something like this:

```
if (!window.AnoJS) {
    window.AnoJS = {};
    // example helper function
    AnoJS.point = function(x, y) { return { x, y }; };
}
```

**Comment by calixo888** [comment]
Nice! We can take a bigger look at this when we have all the contributors get started!
