### ISSUE TITLE
http vs https - mixed content

### ISSUE THREAD

**Issue by neilwave** [anojs/anojs#43]
Browsers block the content.

_Error Message_

Mixed Content: The page at 'https://....' was loaded over HTTPS, but requested an insecure script 'http://anojs.com/...js'. This request has been blocked; the content must be served over HTTPS.

**Comment by sanjaykdragon** [comment]
easy fix:
replace the url with https://anojs.com/...js

**Comment by calixo888** [comment]
It's alright. So the reason why it's only over HTTP is because I'm trying to save some money by putting the website on the free version, which doesn't come with SSL support. After development is finished, I will move it back to the paid version and SSL will be reinstalled :)
