### ISSUE TITLE
Application is down - Internal server Error

### ISSUE THREAD

**Issue by jahantaila** [anojs/anojs#84]
![image](https://user-images.githubusercontent.com/75226884/127392884-1639d27d-9051-477c-99f4-b768e9a4a56e.png)
Server appears to be down

**Comment by jahantaila** [comment]
Server is still down.

**Comment by jahantaila** [comment]
The server is still down today. Is this project maintained anymore?

**Comment by jabo-bernardo** [comment]
Hey, Jahan this issue was already reported to the project owner through the AnoJS discord server and we're still waiting for his response.

**Comment by jahantaila** [comment]
Ok,

**Comment by jahantaila** [comment]
Tell me when its back up
